///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelData {
/*
{
  "token": "eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2NTkzMDI1NjcsImV4cCI6MTY1OTMwMzE2NywiaXNzIjoid3d3LnRlc3QuY29tIiwiYXVkIjoid3d3LnRlc3QuY29tIn0.P-OngkA4BfkAnVPjCcwxN1zYvDlJ2n-UfcPCg0pbQaM7aITM_foJoIhC5v7SRO3aR20845gmUwzndcn7pp05RA",
  "expiration": "2022-08-01T00:32:47.0498499+03:00"
} 
*/

  String? token;
  String? expiration;

  LoginModelData({
    this.token,
    this.expiration,
  });
  LoginModelData.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
    expiration = json['expiration']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['token'] = token;
    data['expiration'] = expiration;
    return data;
  }
}

class LoginModel {
/*
{
  "data": {
    "token": "eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2NTkzMDI1NjcsImV4cCI6MTY1OTMwMzE2NywiaXNzIjoid3d3LnRlc3QuY29tIiwiYXVkIjoid3d3LnRlc3QuY29tIn0.P-OngkA4BfkAnVPjCcwxN1zYvDlJ2n-UfcPCg0pbQaM7aITM_foJoIhC5v7SRO3aR20845gmUwzndcn7pp05RA",
    "expiration": "2022-08-01T00:32:47.0498499+03:00"
  },
  "success": true,
  "message": "Access token oluşturuldu"
} 
*/

  LoginModelData? data;
  bool? success;
  String? message;

  LoginModel({
    this.data,
    this.success,
    this.message,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? LoginModelData.fromJson(json['data']) : null;
    success = json['success'];
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['success'] = success;
    data['message'] = message;
    return data;
  }
}
