///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RegisterModelData {
/*
{
  "token": "eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2NTkzNTI1OTYsImV4cCI6MTY1OTM1MzE5NiwiaXNzIjoid3d3LnRlc3QuY29tIiwiYXVkIjoid3d3LnRlc3QuY29tIn0.K-YpFibmfI44YUYXT_0-hGUlw3CD1WAn8iUNvbFHwGw1w_R1bRkwcwzhkb_D6GYrIKx6TiHsd-2OYCJqDvC24w",
  "expiration": "2022-08-01T14:26:36.5156932+03:00"
} 
*/

  String? token;
  String? expiration;

  RegisterModelData({
    this.token,
    this.expiration,
  });
  RegisterModelData.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
    expiration = json['expiration']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['token'] = token;
    data['expiration'] = expiration;
    return data;
  }
}

class RegisterModel {
/*
{
  "data": {
    "token": "eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTUxMiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2NTkzNTI1OTYsImV4cCI6MTY1OTM1MzE5NiwiaXNzIjoid3d3LnRlc3QuY29tIiwiYXVkIjoid3d3LnRlc3QuY29tIn0.K-YpFibmfI44YUYXT_0-hGUlw3CD1WAn8iUNvbFHwGw1w_R1bRkwcwzhkb_D6GYrIKx6TiHsd-2OYCJqDvC24w",
    "expiration": "2022-08-01T14:26:36.5156932+03:00"
  },
  "success": true,
  "message": "Access token oluşturuldu"
} 
*/

  RegisterModelData? data;
  bool? success;
  String? message;

  RegisterModel({
    this.data,
    this.success,
    this.message,
  });
  RegisterModel.fromJson(Map<String, dynamic> json) {
    data = (json['data'] != null) ? RegisterModelData.fromJson(json['data']) : null;
    success = json['success'];
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['success'] = success;
    data['message'] = message;
    return data;
  }
}
