///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TaskModelData {
/*
{
  "id": 1,
  "categoryName": "Müzik"
} 
*/

  int? id;
  String? categoryName;

  TaskModelData({
    this.id,
    this.categoryName,
  });
  TaskModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    categoryName = json['categoryName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['categoryName'] = categoryName;
    return data;
  }
}

class TaskModel {
/*
{
  "data": [
    {
      "id": 1,
      "categoryName": "Müzik"
    }
  ],
  "success": true,
  "message": "Kategori listelendi"
} 
*/

  List<TaskModelData?>? data;
  bool? success;
  String? message;

  TaskModel({
    this.data,
    this.success,
    this.message,
  });
  TaskModel.fromJson(Map<String, dynamic> json) {
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <TaskModelData>[];
  v.forEach((v) {
  arr0.add(TaskModelData.fromJson(v));
  });
    this.data = arr0;
    }
    success = json['success'];
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    data['success'] = success;
    data['message'] = message;
    return data;
  }
}
